Phase04 c#
Star-Academy/Winter99-Codestar-Alireza-Mohammadian pull request #3
Opened 2021-03-03 17:32 UTC by alirezamhm

2021-03-03 17:49 UTC, BijanEisapour requested changes

2021-03-03 17:49 UTC, BijanEisapour commented on Phase04/console-app/Program.cs
> +    }
<p dir='rtl' align='right'>
تو هر فایل حداکثر یه کلاس بذارید

2021-03-03 17:49 UTC, BijanEisapour commented on Phase04/.gitignore
> +[Ll]ogs/
<p dir='rtl' align='right'>
فایل .gitignore رو باید میذاشتید تو پوشۀ console-app
<br>
الان اون فولدرهایی که باید ignore میشدن، نشدن

2021-03-04 11:52 UTC, alirezamhm commented on Phase04/console-app/Program.cs
> +    }
الان اون دوتا کلاس رو بذارم کنار همین Program.cs
یا باید دایرکتوری library درست کنیم بذاریمشون اونجا؟

2021-03-06 17:06 UTC, BijanEisapour approved these changes

2021-03-06 17:08 UTC, merged