Phase11 web Part 1
Star-Academy/Winter99-Codestar-Alireza-Mohammadian pull request #8
Opened 2021-04-21 13:09 UTC by alirezamhm

2021-05-15 14:10 UTC, BijanEisapour requested changes

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Controllers/SearchEngineController.cs
> +        ISearchEngine Engine;
<p dir='rtl' align='right'>
تا جایی که من کد رو نگاه کردم احساس میکنم Property نیست بنابراین نباید با حرف بزرگ شروع بشه

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Models/Document.cs
> +        public string Content { get; set; }
<p dir='rtl' align='right'>
اگه قراره از get و set پیشفرض استفاده کنی پس چرا اینا رو فیلد در نظر نگرفتی؟ چرا Property هستن؟

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Models/Elastic.cs
> +        }
<p dir='rtl' align='right'>
تو این متدها نیاز نیس اول query رو بریزی تو یه متغیر؛ میتونی مستقیم returnئش کنی

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Models/Elastic.cs
> +            }
<p dir='rtl' align='right'>
به جای اینکه چهار بار متد ToLower رو صدا بزنی، یه بار صداش کن و نتیجه رو بریز تو یه متغیر
<br>
و خیلی بهتره که تو اینجور مواقع از switch استفاده کنی چون خوانایی کد به شدت میره بالا

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Models/FileReader.cs
> +        public string path { get; set; }
<p dir='rtl' align='right'>
اگه Property ئه باید با حرف بزرگ شروع شه
<br>
هر چند که اصن اینجا میتونی از فیلد معمولی استفاده کنی

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Models/SearchEngine.cs
> +            var must_list = MakeMatchQueryList(normals);
<p dir='rtl' align='right'>
چرا camelCase نیست؟

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchApi/Program.cs
> +                });
<p dir='rtl' align='right'>
وقتی یه متدی انقد بزرگه، خوب نیست از Arrow استفاده کنی؛ با همون آکلاد معمولی بنویسی بهتره

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchUI/SearchApp/src/app/home/home.component.html
> +    <img id="background-image" src="assets/Images/Image{{index}}.jpg" />
<p dir='rtl' align='right'>
همیشه واسه تگ img باید اتریبیوتِ alt بذاری و یه توضیح چند کلمه‌ای در مورد محتویات عکس بدی

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchUI/SearchApp/src/app/home/title/title.component.ts
> +  }
<p dir='rtl' align='right'>
اگه به اینا احتیاج نداری پس پاکشون کن

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchUI/SearchApp/src/app/result/header/header.component.scss
> +  font-family: Arial, Helvetica, sans-serif;
<p dir='rtl' align='right'>
بهتره تو کل سایت از یه فونت استفاده کنی
<br>
بنابراین font-family رو بذار تو body

2021-05-15 14:10 UTC, BijanEisapour commented on Phase11/SearchUI/SearchApp/src/app/result/service/documents.service.ts
> +    return results
<p dir='rtl' align='right'>
نباید stringها رو همینجوری رها کنی تو کد
<br>
واسه هر کدوم یه متغیر readonly تو اول کلاس درست کن

2021-05-16 14:40 UTC, alirezamhm commented on Phase11/SearchApi/Models/SearchEngine.cs
> +            var must_list = MakeMatchQueryList(normals);
😂وقتی تو یه روز چنتا زبون سویچ میکنی پیش میاد

2021-05-18 19:01 UTC, merged